### ISSUE TITLE
Add method to return current supported OS versions

### ISSUE THREAD

**Issue by Flipez** [voxpupuli/puppet_metadata#40]
In order to replace our OS logic in vox-pupuli-tasks I need to show the user which versions are currently supported (= not eol yet).

Example of our deprecated logic:

```yaml
support_ranges:
  ubuntu:
    - "18.04"
    - "20.04"
    - "22.04"
```

```ruby
UBUNTU_SUPPORT_RANGE  = VOXPUPULI_CONFIG.dig('support_ranges', 'ubuntu')
UBUNTU_SUPPORT_RANGE".constantize.to_sentence
```

I would like to have a similiar command to `PuppetMetadata::OperatingSystem.latest_release(os))` like `PuppetMetadata::OperatingSystem.supported_releases(os))`
